### ISSUE TITLE
Provide logging as option env variable

### ISSUE THREAD

**Issue by lucmichalski** [varnish/docker-varnish#25]
Hi guys,

Hope you are all well !

Is it possible to add logging to the docker varnish container ?

Could not find how to write the acces.log/error.log file. ^^

Cheers,
Luc Michalski

**Comment by gquintard** [comment]
Hi,

this should help: https://docs.varnish-software.com/tutorials/vsl-query and https://varnish-cache.org/docs/trunk/reference/vsm.html

TL;DR: use a sidecar mounting `/var/lib/varnish` (this is where the shared memory log is), and run either `varnishncsa` or `varnishlog`

**Comment by batandwa** [comment]
`varnishncsa` or `varnishlog` seem to require a running instance `varnishd`. I get _VSM: Could not get hold of varnishd, is it running?_

Am I doing something wrong?  
Here's my compose file:

```
services:
  varnish:
    image: varnish:6.6
    volumes:
      - cache-logs:/var/lib/varnish
  varnish-log:
    image: varnish:6.6
    volumes:
      - cache-logs:/var/lib/varnish
    entrypoint: varnishncsa
```

**Comment by gquintard** [comment]
Hi @batandwa 

The issue is that both `varnishd` and `varnishncsa` will look into `/var/lib/varnish/$HOSTNAME` to write/read the logs. But as they are in different containers, their hostnames are different. The quick fix for you is to use `-n` to tell them exactly where to look:

```
services:
  varnish:
    image: varnish:6.6
    volumes:
      - cache-logs:/var/lib/varnish
    command: [ "-n", "/var/lib/varnish" ]
  varnish-log:
    image: varnish:6.6
    volumes:
      - cache-logs:/var/lib/varnish
    entrypoint: varnishncsa
    command: [ "-n", "/var/lib/varnish" ]

volumes:
  cache-logs:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
```

I'm reopening this ticket, we need to update the image to make this way easier, very possibly by forcing that `-n` parameter by default

**Comment by gquintard** [comment]
https://github.com/docker-library/official-images/pull/9914#event-4558416945

we are now a bit clever and force the `-n` argument to the beginning of `varnish*` commands, which should solve all your issues here

**Comment by namedgraph** [comment]
@gquintard is this still supposed to work with `varnish:7.3.0`? I tried to follow your example in my `docker-compose.yml` config:
```yaml
volumes:
  cache-logs:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  varnish-end-user:
    image: varnish:7.3.0
    user: root # otherwise varnish user does not have permissions to the mounted folder which is owner by root
    tmpfs: /var/lib/varnish/varnishd:exec
    environment:
      - BACKEND_HOST=fuseki-end-user
      - BACKEND_PORT=3030
      - CLIENT_HOST=linkeddatahub
      - VARNISH_TTL=86400
      - VARNISH_SIZE=1G
    entrypoint: /bin/sh -c "cp /etc/varnish/default.vcl.template /etc/varnish/default.vcl && sed -i 's|$${BACKEND_HOST}|'"$$BACKEND_HOST"'|g' /etc/varnish/default.vcl && sed -i 's|$${BACKEND_PORT}|'"$$BACKEND_PORT"'|g' /etc/varnish/default.vcl && sed -i 's|$${CLIENT_HOST}|'"$$CLIENT_HOST"'|g' /etc/varnish/default.vcl && /usr/local/bin/docker-varnish-entrypoint"
    command: [ "-n", "/var/lib/varnish" ]
    volumes:
      - ./platform/varnish.vcl.template:/etc/varnish/default.vcl.template:ro
      - cache-logs:/var/lib/varnish
  varnish-log:
    image: varnish:7.3.0
    #user: root
    volumes:
      - cache-logs:/var/lib/varnish
    entrypoint: varnishncsa
    command: [ "-n", "/var/lib/varnish" ]
```
However I'm getting an error:
```
varnish-log-1       | .....
varnish-log-1       | VSM: Could not get hold of varnishd, is it running?
varnish-log-1 exited with code 1
```
What am I doing wrong?

**Comment by gquintard** [comment]
Hi @namedgraph!

`7.3` isn't supported anymore, so my memory is a bit fuzzy, but:
- you shouldn't have to specify `-n` anymore as the default should be `/var/lib/varnish/varnishd`
- `tmpfs: /var/lib/varnish/varnishd:exec` is probably messing with the `volumes` section, preventing `vanrish-log` from seeing the work directory

You should really upgrade to 7.6, but in the meantime, this works for me:
```
volumes:
  cache-logs:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  varnish-end-user:
    image: varnish:7.3.0
    user: root # otherwise varnish user does not have permissions to the mounted folder which is owner by root
    environment:
      - BACKEND_HOST=fuseki-end-user
      - BACKEND_PORT=3030
      - CLIENT_HOST=linkeddatahub
      - VARNISH_TTL=86400
      - VARNISH_SIZE=1G
    volumes:
      - ./platform/varnish.vcl.template:/etc/varnish/default.vcl.template:ro
      - cache-logs:/var/lib/varnish
  varnish-log:
    image: varnish:7.3.0
    #user: root
    volumes:
      - cache-logs:/var/lib/varnish
    entrypoint: varnishncsa
```

feel free to open a new ticket if you still have issues
