### ISSUE TITLE
Could not get hold of varnishd

### ISSUE THREAD

**Issue by octfx** [varnish/docker-varnish#29]
Using `varnish:fresh` or `varnish:stable` (6.0.7+) no `varnish*` command inside the docker container works.  
Every command outputs `Could not get hold of varnishd, is it running?`

Using versions 6.0.6 or 6.5 all commands successfully connect to the daemon.

Example compose file used:
```
version: '3.7'

services:
  varnish:
    image: varnish:fresh
    restart: unless-stopped
    expose:
      - 80
```

**Comment by gquintard** [comment]
ah, I get it, you are using `varnish*` commands after `exec`'ing in the container right?

We changed things recently so that people could run sidecars more easily: https://github.com/varnish/docker-varnish/commit/3b38b0e1c38c1f6324ac8afa156ff73cfbbffcf4

```
services:
  varnish:
    image: varnish
    volumes:
      - cache-logs:/var/lib/varnish
  varnish-log:
    image: varnish
    volumes:
      - cache-logs:/var/lib/varnish
    command: [varnishncsa]

volumes:
  cache-logs:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
```

but that means by default, `varnishd` will start with `-n /var/lib/varnish`. So, in the current situation, you have two options:
- run the `varnish*` commands with `-n /var/lib/varnish` too so they find the workdir
- run the container with the full command line starting with `/usr/sbin/varnishd -F -f ...` so the entrypoint doesn't inject the argument

I'll check if adding aliases/trampoline scripts could be a better approach to satisfy everyone
