### ISSUE TITLE
Varnish can't find the backend after image recreation

### ISSUE THREAD

**Issue by AtomHare** [varnish/docker-varnish#41]
This issue tracker is meant only for actual bug, and possible feature requests. For help, please use the usual Varnish Cache help channels: https://varnish-cache.org/support/

If you encountered a bug, please include the docker  image tag you are using, as well as the steps to reproduce it.

Hello,

When using the docker image : `varnish:7.0-alpine`, varnish can't find the backend after image recreation. This are the steps needed to reproduce the issue:

1. Use a docker compose with varnish and a backend
e.g
```
services:
    varnish:
        image: varnish:7.0-alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./config/default.vcl:/etc/varnish/default.vcl:ro
        container_name: varnish
        depends_on:
            - backendserver
    backendserver:
        image: backendserver
        restart: unless-stopped
        name: backendserver
```
2. Use the backend localname in varnish config
e.g:
```
vcl 4.0;
backend default {
  .host = "backendserver:8080";
}
```
3. Recreate the backend (e.g happen during a watchtower update)
4. You get a "Error 503 Backend fetch failed" when going on the varnish page (restarting the varnish container fixes it, but not viable to do it on each backend update)

**Comment by gquintard** [comment]
Hi,

This isn't a docker image issue, but an upstream Varnish one. Varnish will resolve "backendserver" into an IP only once, when the configuration is loaded at startup.
When you recreate the backend container, the IP will change, but varnish won't know about that.

You have a few options:
- run `varnishreload` so that varnish reloads the VCL and resolves "backendserver" into the new IP
- on the open-source side, use vmod_dyhttps://github.com/nigoroll/libvmod-dynamic to have varnish track the IP without having to reload the VCL
- if you have access to varnish enterprise, https://docs.varnish-software.com/varnish-cache-plus/vmods/goto/ has a nicer API and is already packaged
- the long term plan could be to send a mail to varnish-misc@varnish-cache.org to gather interest around this feature to potentially add it upstream

**Comment by AtomHare** [comment]
Hi,

Thank you for your quick answer. 
I will try to implement `varnishreload` and I will also send a mail to try to get a long term solution.

P.S: I think it can be interesting for other people encountering the same problem to maybe keep this issue as an open one ?

**Comment by gquintard** [comment]
there's nothing we can do from this repository, so I'm not keen on doing the bookkeeping for upstream. You can however open an issue here (or even better, a PR to https://github.com/docker-library/docs) to mention the issue

**Comment by AtomHare** [comment]
Okay so the workaround in order to "cleanly" fix the problem, is to use a health check that checks if the website throws an error and if yes it reloads varnish in order to update the ip
```
healthcheck:
    test: ash -c "wget --no-verbose --tries=1 --spider 127.0.0.1:80/ || (varnishreload && exit 1)"
    interval: 10s
    timeout: 10s
    retries: 1
```
I hope this will help anyone that encounter this error.
I might look on how to PR https://github.com/docker-library/docs, should I add something like "if the container varnish depends on is recreated varnish will loose it's connection to the container" and point to this issue ?
