### ISSUE TITLE
Question: How to reload default.vcl

### ISSUE THREAD

**Issue by christian-draeger** [varnish/docker-varnish#43]
Hey, 
i try to reload the varnish configuration inside the running container to be able to pass backend default host and port dynamically as environment variables

passing env vars to the container as well as replacing placeholders in the default.vcl is working so far by doing the following in a custom dockerfile:

```Dockerfile
FROM varnish:7.0.0-alpine
LABEL maintainer=caching-reverse-proxy
RUN apk --no-cache add bash
COPY ./cache-config /etc/varnish
RUN chmod +x /etc/varnish/inject-env-vars.sh
RUN /etc/varnish/inject-env-vars.sh #inject env vars to default.vcl
```

Running it via docker compose:
```yaml
version: "3.8"

services:
  varnish:
    container_name: mhub-varnish
    build:
      context: .
      dockerfile: varnish.Dockerfile
    ports:
      - "8090:80"
    environment:
      - VARNISH_SIZE=200M
      - PROXY_HOST=my-backend
      - PROXY_PORT=8081
```

here is my default.vcl:
```
# wire default backend
backend default {   
    .host = "${PROXY_HOST}";
    .port = "${PROXY_PORT}";
    .probe = {
            .url = "/actuator/health";
            .timeout = 1s;
            .interval = 5s;
            .window = 5;
            .threshold = 3;
        }
}
```

here is my inject-env-vars.sh:
```bash
#!/bin/bash
envs=`printenv`

echo $envs

for env in $envs
do
    IFS== read name value <<< "$env"

    sed -i "s|\${${name}}|${value}|g" /etc/varnish/default.vcl
done
```

after starting the container via docker compose and connecting against it using `docker run -it --rm mhub-varnish /bin/sh` i can see that my environment variables are there (```echo `printenv` ```). when i run my bash script to replace all placeholders in the default.vcl via `./inject-env-vars.sh` i can see that that my placeholders have been successfully replaced inside the default.vcl

so far so good!

Now i have to manage to make varnish reload the default.vcl 
In the [varnish docs](https://varnish-cache.org/docs/6.6/tutorial/starting_varnish.html) (on the bottom of the linked page) i is saying 
> Now issue `service varnish reload` to make Varnish reload it’s configuration.

but if i try that inside my container i get the following:
```
/etc/varnish # service varnish reload
/bin/sh: service: not found
```

How to make the dockerized varnish reload the config?
