### ISSUE TITLE
tmpfs unusable after container restart

### ISSUE THREAD

**Issue by tmuncks** [varnish/docker-varnish#53]
Using `tmpfs` does not work properly, after container restart.

```
version: '3.1'
services:
  varnish:
    image: "varnish:latest"
    restart: "always"
    volumes:
      - "./varnish.vcl:/etc/varnish/default.vcl:ro"
    tmpfs:
      - "/var/lib/varnish/varnishd:exec"
```

When the `/var/lib/varnish/varnishd` path already exists, docker does strange things when mounting a tmpfs. The end result is:

First run:

```
drwxrwxrwt 2 root    root      40 Apr 24 00:40 varnishd
```

After `docker-compose restart varnish`:

```
drwxr-xr-x 2 root    root      40 Apr 24 00:40 varnishd
```

This in turn gives:

```
varnish_1    | Error: Cannot create test-file in /var/lib/varnish/varnishd (Permission denied)
varnish_1    | Check permissions (or delete old directory)
varnish_1    | (-? gives usage)
```

This has not been an issue previously, so my suspicions go to the `USER varnish` statement that was recently added near the bottom of the `Dockerfile`?

**Comment by tmuncks** [comment]
Just double checked that older builds (e.g. 6.6 and 7.0.1) does not exhibit this problem.

**Comment by gquintard** [comment]
hi @tmuncks, can you detail how to reproduce this please? I used you `yaml` file, ran `docker-compose up` and in another terminal ran `docker-compose restart`, and I get the container stuck in the `restarting` state (which isn't great, but also happens on `7.0.1`), but I don't get the error message you shared

**Comment by tmuncks** [comment]
I think you are precisely experiencing this problem. The actual messages are in the log:
```
docker-compose logs varnish
```

For good measure, this is how I'm able to reproduce 100% of the time:
```
root@example:/docker/test# docker-compose up -d --force-recreate
Recreating test_varnish_1 ... done

root@example:/docker/test# docker-compose logs varnish
Attaching to test_varnish_1
varnish_1  | Debug: Version: varnish-7.1.0 revision c2c07517ddddbc187604b800eff733296e93aaad
varnish_1  | Debug: Platform: Linux,5.15.0-25-generic,x86_64,-jnone,-smalloc,-sdefault,-hcritbit
varnish_1  | Debug: Child (20) Started
varnish_1  | Child launched OK
varnish_1  | Info: Child (20) said Child starts

root@example:/docker/test# docker-compose restart varnish
Restarting test_varnish_1 ... done

root@example:/docker/test# docker-compose logs varnish
Attaching to test_varnish_1
varnish_1  | Debug: Version: varnish-7.1.0 revision c2c07517ddddbc187604b800eff733296e93aaad
varnish_1  | Debug: Platform: Linux,5.15.0-25-generic,x86_64,-jnone,-smalloc,-sdefault,-hcritbit
varnish_1  | Debug: Child (20) Started
varnish_1  | Child launched OK
varnish_1  | Info: Child (20) said Child starts
varnish_1  | Error: Manager got SIGTERM
varnish_1  | Debug: Stopping Child
varnish_1  | Info: Child (20) ended
varnish_1  | Info: Child (20) said Child dies
varnish_1  | Debug: Child cleanup complete
varnish_1  | Info: manager stopping child
varnish_1  | Info: manager dies
varnish_1  | Error: Cannot create test-file in /var/lib/varnish/varnishd (Permission denied)
varnish_1  | Check permissions (or delete old directory)
varnish_1  | (-? gives usage)
varnish_1  | Error: Cannot create test-file in /var/lib/varnish/varnishd (Permission denied)
varnish_1  | Check permissions (or delete old directory)
varnish_1  | (-? gives usage)
varnish_1  | Error: Cannot create test-file in /var/lib/varnish/varnishd (Permission denied)
varnish_1  | Check permissions (or delete old directory)
varnish_1  | (-? gives usage)
varnish_1  | Error: Cannot create test-file in /var/lib/varnish/varnishd (Permission denied)
varnish_1  | Check permissions (or delete old directory)
varnish_1  | (-? gives usage)
```

**Comment by gquintard** [comment]
thanks, that's useful. The permission change here is really hurting us...

The easy fix is to add `user: root` to your file:

``` yaml
version: '3.1'
services:
  varnish:
    image: "varnish:latest"
    restart: "always"
    volumes:
      - "./varnish.vcl:/etc/varnish/default.vcl:ro"
    tmpfs:
      - "/var/lib/varnish/varnishd:exec"
    user: root
```

But of course, this loses you the unprivileged behavior, which is annoying.

I need some time to understand why `docker-compose` changes the permissions
