### ISSUE TITLE
`VARNISH_TTL` env has no effect

### ISSUE THREAD

**Issue by namedgraph** [varnish/docker-varnish#76]
```yaml
  varnish:
    image: varnish:7.3.0
    environment:
      - VARNISH_TTL=86400
      - VARNISH_SIZE=1G
```
I've been using this configuration for a long time (possibly starting with my own Docker image for Varnish) but only now (using version 7.3.0) have I noticed that the `$VARNISH_TTL` value has no effect and the TTL seems to default to 120 😅 

Has this never worked in the official image or is something broken?
There is a PR #73 [mentioning `VARNISH_TTL`](https://github.com/varnish/docker-varnish/pull/73#issuecomment-1913553820) but it does not seem that it actually introduces support for it?

How should I specify the default TTL using a `docker-compose` config?
